fieldLayouts:
  219c4c8a-c48f-402d-ac26-598afc07c0c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Inventory Sale'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dc7f3fec-946b-4b2a-b5dd-6d48f4019116
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 013b5064-e06b-4464-99dc-5c6736b1647c # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 202dc2f5-da26-493e-bc5a-cad16a00adf0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f541b1c1-b121-4c59-a4ec-dae0a312e66e # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 966dbd16-aff5-4a63-8e38-f12e112c804c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c057b053-4155-4d39-bb1b-51c48091561c # Inventory Sale
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8800e3a-0e8a-45a2-86f2-78d45fee8e31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54722379-1bb0-4018-9583-711195e2eb5b
        userCondition: null
handle: inventorySale
hasTitleField: true
name: 'Inventory Sale'
section: 2460a09b-1b47-4ec1-8a88-08f3829af23b # Inventory Sale
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
