fieldLayouts:
  343f54fb-2025-463d-8841-f90552fc7643:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c7439b2c-cc7c-41ce-a73e-d6999494db87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 013b5064-e06b-4464-99dc-5c6736b1647c # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8ac7435-8b32-4aaa-a135-baaedd50b48d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f541b1c1-b121-4c59-a4ec-dae0a312e66e # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19faa1e5-c754-483a-a8f6-c1e341750710
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a9ad7290-97e7-4a45-aa4b-a085c5050332 # Brands
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46c3aec9-f9d7-4389-87f2-0545f13a1c1c
            userCondition: null
            warning: null
            width: 100
        name: 'Lines We Carry'
        uid: 4c909bfe-be7d-4daf-b8fc-06237c76104d
        userCondition: null
handle: linesWeCarry
hasTitleField: true
name: 'Lines We Carry'
section: 2f3b9c57-35b4-4a90-bcd7-eb84a0b7f82a # Lines We Carry
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
