baseUrl: 'https://distinctiveaudio.ca'
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Distinctive Audio'
primary: true
siteGroup: b1cf6c9f-576f-451e-bc2c-2e114380c9f6 # Distinctive Audio
sortOrder: 1
