fieldLayouts:
  17c4f8fc-2785-47f8-a610-4512f944d5d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 31434be6-992b-4c66-889f-133bf3b4bd0b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82a60a37-e5aa-4b23-8de5-c10206fb2af7
        userCondition: null
fs: newArrivals
handle: newArrivals
name: 'New Arrivals'
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
