fieldLayouts:
  4d37fe69-14d8-44d1-a3c2-0fb8d6b07db5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 517325b4-8919-4cd2-986a-98256ee6692c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fd7b6ff2-8ede-43b9-a8fc-115a8585a7dc
        userCondition: null
fs: productImages
handle: productImages
name: 'Product Images'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
