fieldLayouts:
  9d8feefd-00c6-499d-b5de-8fcf3c17399a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: tradeIns
hasUrls: true
name: 'Trade Ins'
settings:
  path: '@root/web/images/trade-ins'
sortOrder: 6
type: craft\volumes\Local
url: '@web/images/trade-ins'
