columnSuffix: null
contentColumnType: string
fieldGroup: e27faff0-dc9b-47f6-87a7-ff017f1c9387 # Lines We Carry
handle: brands
instructions: 'Enter brand information'
name: Brands
searchable: true
settings:
  contentTable: '{{%matrixcontent_brands}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
