contentColumnType: string
fieldGroup: e27faff0-dc9b-47f6-87a7-ff017f1c9387
handle: brands
instructions: 'Enter brand information'
name: Brands
searchable: true
settings:
  contentTable: '{{%matrixcontent_brands}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
