columnSuffix: null
contentColumnType: text
fieldGroup: b406058a-faea-4d8a-af1c-c58f1515c881 # Home
handle: locationAndHours
instructions: 'Enter location and hours description'
name: 'Location and Hours'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: 'Enter location and hours description.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
