columnSuffix: null
contentColumnType: string
fieldGroup: ac92f2e6-6c48-48a5-bbbc-1d5cc82fb563 # Common
handle: productImage
instructions: 'Select product image'
name: 'Product Image'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:8f369514-5b46-49c6-9fd2-5db66f81e30e' # Product Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:dc3f54b5-b44c-4cc9-b7e6-b93aacfc1b2e' # Banners
  restrictedLocationSubpath: null
  selectionLabel: 'Add a product image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
