columnSuffix: null
contentColumnType: string
fieldGroup: ac92f2e6-6c48-48a5-bbbc-1d5cc82fb563 # Common
handle: specialsImage
instructions: 'Add specials product image'
name: 'Specials Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:dc3f54b5-b44c-4cc9-b7e6-b93aacfc1b2e' # Banners
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:58b14f3f-0f2b-4588-a6c1-067f772a101f' # Specials
  restrictedLocationSubpath: null
  selectionLabel: 'Add specials product image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
