columnSuffix: null
contentColumnType: string
fieldGroup: ac92f2e6-6c48-48a5-bbbc-1d5cc82fb563 # Common
handle: tradeInsImage
instructions: 'Add trade in product image'
name: 'Trade Ins Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:dc3f54b5-b44c-4cc9-b7e6-b93aacfc1b2e' # Banners
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:6b676c34-3f5a-4a09-8489-a4475c51a42a' # Trade Ins
  restrictedLocationSubpath: null
  selectionLabel: 'Add trade in product image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
