contentColumnType: text
fieldGroup: b406058a-faea-4d8a-af1c-c58f1515c881
handle: tubeTesting
instructions: 'Enter tube testing description'
name: 'Tube Testing'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: 'Enter tube testing description.'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
