dateModified: 1689624997
email:
  fromEmail: rheal@distinctiveaudio.ca
  fromName: 'Distinctive Audio'
  replyToEmail: null
  template: null
  transportSettings:
    encryptionMethod: tls
    host: smtp.mailgun.org
    password: b18505a4b79a7c46b93f4d7052db489b-48c092ba-8aea63a4
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: postmaster@mg.distinctiveaudio.ca
  transportType: craft\mail\transportadapters\Smtp
fs:
  banners:
    hasUrls: true
    name: Banners
    settings:
      path: '@root/web/images/banners'
    type: craft\fs\Local
    url: '@web/images/banners'
  brandLogos:
    hasUrls: true
    name: 'Brand Logos'
    settings:
      path: '@root/web/images/brand-logos'
    type: craft\fs\Local
    url: '@web/images/brand-logos'
  newArrivals:
    hasUrls: true
    name: 'New Arrivals'
    settings:
      path: '@root/web/images/new-arrivals'
    type: craft\fs\Local
    url: '@web/images/new-arrivals'
  productImages:
    hasUrls: true
    name: 'Product Images'
    settings:
      path: '@root/web/images/product-images'
    type: craft\fs\Local
    url: '@web/images/product-images'
  specials:
    hasUrls: true
    name: Specials
    settings:
      path: '@root/web/images/specials'
    type: craft\fs\Local
    url: '@web/images/specials'
  staffMembers:
    hasUrls: true
    name: 'Staff Members'
    settings:
      path: '@root/web/images/staff-members'
    type: craft\fs\Local
    url: '@web/images/staff-members'
  tradeIns:
    hasUrls: true
    name: 'Trade Ins'
    settings:
      path: '@root/web/images/trade-ins'
    type: craft\fs\Local
    url: '@web/images/trade-ins'
meta:
  __names__:
    0a7cb1ae-b730-4b9d-8de3-31f622be61e1: 'Inventory Section' # Inventory Section
    00c0a703-b18a-420f-808a-05a212fceb47: 'New Arrivals' # New Arrivals
    0f785581-fb1e-4dcb-a8a6-b318ef2442ec: Announcements # Announcements
    1bf898bb-8fd9-4621-936f-a0a626830661: 'Equipment Repair' # Equipment Repair
    1dff14a0-d227-444f-800f-5ac052fdc27d: Brand # Brand
    1e14e2c5-fcf0-4386-9b31-cb3a27e26e14: 'New Arrivals' # New Arrivals
    2f3b9c57-35b4-4a90-bcd7-eb84a0b7f82a: 'Lines We Carry' # Lines We Carry
    3e0bb0e9-ac24-4c00-ae6e-7b23864b9946: 'Staff Member Image' # Staff Member Image
    4ae1a81a-56e1-40ce-89d2-dbc006382d5e: 'Brand Logo' # Brand Logo
    4dbee5b3-ba1a-43ce-91c8-4bf029ef2081: 'Our Services' # Our Services
    5f49df0f-6f46-4dbd-af5b-903eb9c262e3: 'Staff Member Occupation' # Staff Member Occupation
    6a913914-bdde-4106-89c6-7c202839dfbe: 'Staff Member Image' # Staff Member Image
    6b676c34-3f5a-4a09-8489-a4475c51a42a: 'Trade Ins' # Trade Ins
    6c648785-b306-40ae-a0eb-881bc67ac892: About # About
    6e538d3c-c170-41bb-91a8-a1018f85b65e: About # About
    8a1fe93d-b584-4313-8ffe-97e79c98c562: Schedule # Schedule
    8b8fa979-09c6-4e91-9a95-4a37a6f1d367: Subtitle # Subtitle
    8ce95efd-5e56-4aaf-a893-a092eab8c61b: Contact # Contact
    8f369514-5b46-49c6-9fd2-5db66f81e30e: 'Product Images' # Product Images
    10db8795-5329-421c-ae69-e9662e5835af: '120x80 Thumb' # 120x80 Thumb
    013b5064-e06b-4464-99dc-5c6736b1647c: 'Banner Image' # Banner Image
    18e7a260-0b40-43fb-994b-5dc950d19d8f: 'Tube Testing' # Tube Testing
    23f50ca4-df67-4771-a225-d315082a3d80: 'Product Description' # Product Description
    49d5d307-05b5-4d1a-9d26-2f6f1765e504: 'Location and Hours' # Location and Hours
    58b14f3f-0f2b-4588-a6c1-067f772a101f: Specials # Specials
    85e155b1-ff4f-4a9e-a292-00163653b845: 'Inventory Table' # Inventory Table
    275ad980-870c-4c7b-a262-f73ab2433010: 'Alt Field' # Alt Field
    457e7f25-eb5d-4d55-a592-75d06bb9d2c9: 'Thank You' # Thank You
    550b919c-b0a2-4efa-90bf-31e7777d5349: 'Trade Ins' # Trade Ins
    0577a5d0-62be-4944-ba86-f183c589c93a: 'Inventory Announcements' # Inventory Announcements
    781b9b88-1145-41db-a1ec-404c4eb16053: '1440x1080 Thumb' # 1440x1080 Thumb
    854a442b-10ac-48ca-9457-705a08261601: 'New Arrivals Home' # New Arrivals Home
    979ca7fe-e7ec-470f-816c-edce9710a523: Contact # Contact
    2460a09b-1b47-4ec1-8a88-08f3829af23b: 'Inventory Sale' # Inventory Sale
    3784b452-c0ac-4df7-85e6-4838f0d2e179: 'Product Type' # Product Type
    7160f499-42c6-4569-bb6d-408e3b3b12ac: 'Staff Members' # Staff Members
    9365cf29-21e5-4c57-bf70-53d9936bc0cc: 'Trade Ins Image' # Trade Ins Image
    9541ca9c-94ec-4d17-b90c-0c9abb1c10e4: 'Inventory Table' # Inventory Table
    66501f16-0793-48a0-a3d3-c417f87dd281: 'Staff Members' # Staff Members
    87561c62-c9a2-422f-aee7-36748071db5a: 'Listening Demos' # Listening Demos
    169431be-1647-438f-b788-bb1be2f2a5b6: 'New Arrivals' # New Arrivals
    485229ad-9a4d-4716-9416-38d949e7375b: 'New Arrivals Home' # New Arrivals Home
    4424988d-4e34-40a6-98fb-0daf0428595a: 'Brand Link' # Brand Link
    55627598-7306-4231-9fd0-426030671f1a: Specials # Specials
    58559379-0f35-4555-b522-a6551550a19d: Home # Home
    a2a74b6e-84bd-4382-8378-82795f25b1d6: 'Custom Cables' # Custom Cables
    a9ad7290-97e7-4a45-aa4b-a085c5050332: Brands # Brands
    a16b48a6-e0e5-4d2b-8af7-97f71004a903: 'Distinctive Audio' # Distinctive Audio
    a8407db5-5f48-48b2-843a-cf5f3da16559: Home # Home
    ac92f2e6-6c48-48a5-bbbc-1d5cc82fb563: Common # Common
    aed23190-01f0-49ee-b4dc-6da079daced7: 'Product Brand' # Product Brand
    b1cf6c9f-576f-451e-bc2c-2e114380c9f6: 'Distinctive Audio' # Distinctive Audio
    b440f215-9400-4161-af1f-3fdcfbcc5ec4: 'Alt Field' # Alt Field
    b717c53c-d0a7-4e3f-baed-f70fb8d7326b: Footer # Footer
    b406058a-faea-4d8a-af1c-c58f1515c881: Home # Home
    b6911359-fa1d-4a5e-b105-a8dbba4ba311: Contact # Contact
    ba9bfa6b-8835-4be3-9b21-1286a5d4e499: 'Product Image' # Product Image
    bc43f9f9-84ed-490f-8238-350906202c1c: 'Thank You' # Thank You
    bd21f847-bc85-4d4d-ad12-2cdde91e2161: Product # Product
    c05a65e1-c0f7-4fe8-bdef-0320631b8a6c: 'Sale Price' # Sale Price
    c057b053-4155-4d39-bb1b-51c48091561c: 'Inventory Sale' # Inventory Sale
    c4b57835-5b96-4ec4-a5e9-94ca2bc51000: 'Suggested Retail Price' # Suggested Retail Price
    cb11528e-3c70-4310-a650-9489ab6cab2a: 'Staff Member Name' # Staff Member Name
    d0d4216e-2763-46e1-bfb3-6a6a7008d0ed: 'Brand Logo' # Brand Logo
    d4abbd3f-cf1e-4be5-a393-09cb07079e8e: 'Staff Member Image' # Staff Member Image
    d6e09519-1881-43ab-bbc7-95dfce57ab30: 'Specials Image' # Specials Image
    d888ab54-bc47-47c1-aeea-2675c677f52e: 'New Arrivals' # New Arrivals
    dc3f54b5-b44c-4cc9-b7e6-b93aacfc1b2e: Banners # Banners
    e07d3e39-bda1-4699-8433-893b8b53d798: 'Lines We Carry' # Lines We Carry
    e4ad0170-730e-444c-b8fb-aa67b567ae75: 'Public Schema' # Public Schema
    e7e0da6f-770c-47f4-a2a0-4753bc1b4850: 'Brand Logos' # Brand Logos
    e9d4674e-d79e-4dee-857d-ee7af1af938c: 'Product Image' # Product Image
    e27faff0-dc9b-47f6-87a7-ff017f1c9387: 'Lines We Carry' # Lines We Carry
    ec3e3024-d0fd-4bf1-980e-8d13cd7d20e2: 'Inventory Sale' # Inventory Sale
    f74eac5c-479e-44ce-9dba-e672ea69d4c0: 'New Arrivals Image' # New Arrivals Image
    f541b1c1-b121-4c59-a4ec-dae0a312e66e: Description # Description
    f7286ad0-bbbb-40db-aa97-cbf3101f69f1: 'Product Image' # Product Image
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: ''
      prependSubject: ''
      successFlashMessage: 'Your message has been sent.'
      toEmail: rheal@distinctiveaudio.ca
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      honeypotParam: fromPhone
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 3CE0EO5YYJOKZ78Y1EI9F8L3
    schemaVersion: 3.0.12
  tablemaker:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: 'Distinctive Audio'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
