dateModified: 1620771395
email:
  fromEmail: rheal@distinctiveaudio.ca
  fromName: 'Distinctive Audio'
  replyToEmail: null
  template: null
  transportSettings:
    encryptionMethod: tls
    host: smtp.mailgun.org
    password: 438a0443c9ec2b687d330b76faf8529c-77751bfc-d8fbd203
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: postmaster@mg.distinctiveaudio.ca
  transportType: craft\mail\transportadapters\Smtp
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: ''
      prependSubject: ''
      successFlashMessage: 'Your message has been sent.'
      toEmail: rheal@distinctiveaudio.ca
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      honeypotParam: fromPhone
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  tablemaker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Distinctive Audio'
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
