defaultPlacement: end
enableVersioning: true
handle: inventorySale
name: 'Inventory Sale'
propagationMethod: all
siteSettings:
  a16b48a6-e0e5-4d2b-8af7-97f71004a903: # Distinctive Audio
    enabledByDefault: true
    hasUrls: true
    template: inventory-sale/_entry
    uriFormat: da-inventory-sale
type: single
