defaultPlacement: end
enableVersioning: true
handle: linesWeCarry
name: 'Lines We Carry'
propagationMethod: all
siteSettings:
  a16b48a6-e0e5-4d2b-8af7-97f71004a903: # Distinctive Audio
    enabledByDefault: true
    hasUrls: true
    template: lines-we-carry/_entry
    uriFormat: lines-we-carry
type: single
